import cmath
a=int(input('Enter a :'))
b=int(input('Enter b :'))
c=int(input('Enter c :'))
dis = (b**2) - (4 * a*c)
root1 = (-b-cmath.sqrt(dis))/(2 * a)
root2 = (-b + cmath.sqrt(dis))/(2 * a)
print('The roots are : ')
print(root1)
print(root2)
